# CMake generated Testfile for 
# Source directory: /tmp/workspace/xexes/sevenzipjbinding
# Build directory: /tmp/workspace/xexes/sevenzipjbinding/build-test
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(JUnit-common "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Common tests" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-common PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;409;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-common-no-privileged-init "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Common tests" "-D" "JAVA_OPT=-Dsevenzip.no_doprivileged_initialization%3D1" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-common-no-privileged-init PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;410;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-init-std-1 "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Init tests (Std) 1" "-D" "JAVA_OPT=-Dsevenziptest.standard_initialization_test_phase%3D1" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-init-std-1 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;412;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-init-std-2 "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Init tests (Std) 2" "-D" "JAVA_OPT=-Dsevenziptest.standard_initialization_test_phase%3D2" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-init-std-2 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;413;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-init-verify-1 "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Init tests (Verify) 1" "-D" "JAVA_OPT=-Dsevenziptest.standard_initialization_test_phase%3D1" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-init-verify-1 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;415;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-init-verify-2 "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Init tests (Verify) 2" "-D" "JAVA_OPT=-Dsevenziptest.standard_initialization_test_phase%3D2" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-init-verify-2 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;416;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-tools "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Tools tests" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-tools PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;418;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-snippets "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Snippets tests" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-snippets PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;419;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-snippets-no-privileged-init "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Snippets tests" "-D" "JAVA_OPT=-Dsevenzip.no_doprivileged_initialization%3D1" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-snippets-no-privileged-init PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;420;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-encoding-utf-8 "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Encoding tests 1" "-D" "JAVA_OPT=-Dfile.encoding%3DUTF8" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-encoding-utf-8 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;422;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-encoding-cp1252 "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Encoding tests 2" "-D" "JAVA_OPT=-Dfile.encoding%3DCP1252" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-encoding-cp1252 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;423;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-encoding-cp1251 "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Encoding tests 3" "-D" "JAVA_OPT=-Dfile.encoding%3DCP1251" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-encoding-cp1251 PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;424;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-bug-reports "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Bug report tests" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-bug-reports PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;426;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-single-file-extraction "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Single file tests" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-single-file-extraction PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;427;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-multiple-files-extraction "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Multiple files tests" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-multiple-files-extraction PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;428;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-compression "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Compression tests" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-compression PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;429;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-badarchive "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Bad archive tests" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-badarchive PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;430;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
add_test(JUnit-misc "/usr/local/bin/cmake" "-D" "RUNTIME_JAVA_OPTS=$ENV{RUNTIME_JAVA_OPTS}" "-D" "SINGLEBUNDLE=Misc tests" "-P" "/tmp/workspace/xexes/sevenzipjbinding/build-test/JUnitRunner.cmake")
set_tests_properties(JUnit-misc PROPERTIES  _BACKTRACE_TRIPLES "/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;431;add_test;/tmp/workspace/xexes/sevenzipjbinding/CMakeLists.txt;0;")
subdirs("jbinding-cpp")
